[package]
name = "complete-io"
version = "0.1.0"

[dependencies]
futures = "^0.1.17"
tokio-core = { version = "^0.1.10", optional = true }
mio = { verison = "^0.6.11", optional = true }
net2 = { version = "^0.2.31", optional = true }

miow = { version = "^0.2.1", optional = true }
winapi = { version = "^0.2.8", optional = true }
ws2_32-sys = { version = "^0.2.1", optional = true }

[features]
default = ["tokio", "iocp"]
tokio = ["tokio-core", "mio"]
iocp = ["miow", "winapi", "ws2_32-sys", "net2"]